# Generated by Django 3.2.11 on 2025-03-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_agences1'),
        ('home', '0006_contact'),
    ]

    operations = [
    ]
