# Generated by Django 3.2.11 on 2025-03-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_agency_image'),
        ('home', '0007_merge_0004_agences1_0006_contact'),
    ]

    operations = [
    ]
